package:
  name: numba
  version: {{ environ.get('GIT_DESCRIBE_TAG','') }}

source:
  git_url: git@github.com:numba/numba.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # This is needed to preserve extended setuptools metadata
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - argparse        [py26]
    - numpy
    # On channel https://binstar.org/numba/
    - llvmlite
    - funcsigs       [py26 or py27]
test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
    - cudatoolkit
  files:
    - mandel.py
  commands:
    - pycc -h
