package:
   name: numba
   version: 99.9.9

source:
  git_url: https://github.com/numba/numba.git
  git_tag: devel

build:
  # This is needed to preserve extended setuptools metadata
  preserve_egg_dir: yes

requirements:
  build:
    - numpy
    #- chrpath         [linux]
    - python
    #- llvmmath
  run:
    - python
    - argparse        [py26]
    - numpy
    - llvmpy
    #- llvmmath

test:
  requires:
    - unittest2       [py26]
  files:
    - mandel.py
  commands:
    - pycc -h
    - numba -h

