package:
  name: numba
  version: "0.16dev1"

source:
  path: ../..
  #git_url: git@github.com:numba/numba.git

build:
  number: 1
  # This is needed to preserve extended setuptools metadata
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - argparse        [py26]
    - numpy
    # On channel https://binstar.org/numba/
    - llvmlite

test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
    - cudatoolkit
  files:
    - mandel.py
  commands:
    - pycc -h
